---
version: "1"
services:
  db:
    container_name: sql_db
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicles_db
  mvc:
    container_name: mvc
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      DB_CONNECTION_STRING: Host=db;Database=vehicles_db;Port=5432;UserId=postgres;password=postgres
volumes:
  postgres:


